const wordList = [
  { word: "javascript", hint: "A popular programming language for the web" },
  { word: "python", hint: "A programming language named after a snake" },
  { word: "hangman", hint: "The name of this very game" },
  { word: "apple", hint: "A famous tech company and also a fruit" },
  { word: "tesla", hint: "Electric car company founded by Elon Musk" },
  { word: "pakistan", hint: "A country in South Asia" },
  { word: "mountain", hint: "A large natural elevation of the earth" },
  { word: "lion", hint: "The king of the jungle" },
  { word: "sunflower", hint: "A yellow flower that follows the sun" },
  { word: "guitar", hint: "A musical instrument with strings" },
  { word: "notebook", hint: "Used by students to write notes" },
  { word: "butterfly", hint: "An insect with colorful wings" },
  { word: "rainbow", hint: "Appears after rain with seven colors" },
  { word: "football", hint: "Popular sport played with a round ball" },
  { word: "instagram", hint: "A social media app for sharing photos" },
  { word: "chocolate", hint: "Sweet treat made from cocoa" },
  { word: "pizza", hint: "Famous Italian food with cheese and toppings" },
  { word: "computer", hint: "Electronic device for processing data" },
  { word: "ocean", hint: "A vast body of salt water" },
  { word: "diamond", hint: "A precious gemstone" },
  { word: "camera", hint: "Device used to capture images" },
  { word: "kangaroo", hint: "Animal native to Australia with a pouch" },
  { word: "volcano", hint: "A mountain that erupts lava" },
  { word: "dragon", hint: "Mythical creature that breathes fire" },
  { word: "bicycle", hint: "Two-wheeled vehicle powered by pedaling" },
  { word: "galaxy", hint: "A system of stars and planets in space" },
  { word: "icecream", hint: "Cold sweet dessert loved by all" },
  { word: "library", hint: "A place full of books" },
  { word: "paris", hint: "Capital city of France" },
  { word: "twitter", hint: "A social media platform with tweets" },
];
